version: '3.8'
services:
    db:
        image: postgres:14
        container_name: postgres
        volumes:
            - ./tmp/pg:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dating-app
networks:
    app_network:
        driver: bridge
